version: '3.5'
services:
  ssm-confd:
    image: 630201600234.dkr.ecr.eu-west-1.amazonaws.com/tamima-ssm_confd:awsug-nginx-1.1.2
    #image: awsug-nginx-1.1.2
    build: .
    container_name: ssm-confd
    ports:
      - 80:80
    network_mode: host
    environment:
      - SSM_ENABLED=true
      - AWS_REGION=eu-west-1
      - PREFIX=/tamima
      - AWS_PROFILE
      - CONFD_INTERVAL=10
    volumes:
      - ~/.aws:/root/.aws